//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoReinforcer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoReinforcer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns must be a valid positive integer.
        /// </summary>
        internal static string ErrorButtonColumns {
            get {
                return ResourceManager.GetString("ErrorButtonColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height must be a valid positive integer.
        /// </summary>
        internal static string ErrorButtonHeight {
            get {
                return ResourceManager.GetString("ErrorButtonHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be set.
        /// </summary>
        internal static string ErrorButtonName {
            get {
                return ResourceManager.GetString("ErrorButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video must be set to the location of a valid video file.
        /// </summary>
        internal static string ErrorButtonVideoLocation {
            get {
                return ResourceManager.GetString("ErrorButtonVideoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width must be a valid positive integer.
        /// </summary>
        internal static string ErrorButtonWidth {
            get {
                return ResourceManager.GetString("ErrorButtonWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is invalid.
        /// </summary>
        internal static string ErrorInvalidFile {
            get {
                return ResourceManager.GetString("ErrorInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings are invalid.
        /// </summary>
        internal static string ErrorInvalidSettings {
            get {
                return ResourceManager.GetString("ErrorInvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video failed: {0}.
        /// </summary>
        internal static string ErrorMediaFailure {
            get {
                return ResourceManager.GetString("ErrorMediaFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file.
        /// </summary>
        internal static string ErrorOpeningFile {
            get {
                return ResourceManager.GetString("ErrorOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file.
        /// </summary>
        internal static string ErrorSavingFile {
            get {
                return ResourceManager.GetString("ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MoveText {
            get {
                return ResourceManager.GetString("MoveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Files (*.bmp;*.gif;*.jpg;*.png)|*.bmp;*.gif;*.jpg;*.png|All Files (*.*)|*.*.
        /// </summary>
        internal static string OpenImageFilter {
            get {
                return ResourceManager.GetString("OpenImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml)|*.xml|All Files (*.*)|*.*.
        /// </summary>
        internal static string OpenSettingsFilter {
            get {
                return ResourceManager.GetString("OpenSettingsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Files (*.avi;*.mpg;*.wmv)|*.avi;*.mpg;*.wmv|All Files (*.*)|*.*.
        /// </summary>
        internal static string OpenVideoFilter {
            get {
                return ResourceManager.GetString("OpenVideoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (.xml)|*.xml.
        /// </summary>
        internal static string SaveSettingsFilter {
            get {
                return ResourceManager.GetString("SaveSettingsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        internal static string SettingsExtension {
            get {
                return ResourceManager.GetString("SettingsExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video {0}.
        /// </summary>
        internal static string VideoWindowTitle {
            get {
                return ResourceManager.GetString("VideoWindowTitle", resourceCulture);
            }
        }
    }
}
